<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Admin_SRV-PC" name="Listners.RetryFailedcases" tests="6" failures="0" timestamp="2022-04-11T16:53:49 IST" time="0.016" errors="1">
  <testcase name="Test2" time="0.005" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase name="Test2" time="0.000" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase name="Test2" time="0.001" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase name="Test2" time="0.000" classname="Listners.RetryFailedcases">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Listners.RetryFailedcases.Test2(RetryFailedcases.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase name="Test2" time="0.010" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase name="Test2" time="0.000" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <system-out/>
</testsuite> <!-- Listners.RetryFailedcases -->
